language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=1.4.16
  - DJANGO=1.6.8
  - DJANGO=1.7.1

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4.16
    - python: 3.3
      env: DJANGO=1.6.8
    - python: 3.4
      env: DJANGO=1.4.16
    - python: 3.4
      env: DJANGO=1.6.8

branches:
  only:
    - master
    - develop

install:
  - "pip install coverage==3.7"
  - "pip install python-coveralls==2.4.0"
  - "pip install Django==$DJANGO"
  - "pip install -e ."

script:
    coverage run --rcfile=.coverage.rc runtests.py
