language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO=1.4.21
  - DJANGO=1.7.9
  - DJANGO=1.8.3

matrix:
  exclude:
    - python: 3.4
      env: DJANGO=1.4.21
    - python: 3.4
      env: DJANGO=1.7.9

branches:
  only:
    - master
    - develop

install:
  - "pip install Django==$DJANGO"
  - "pip install -e ."

script:
    python runtests.py
