language: python
python:
  - "2.7"
  - "3.3"
install:
  - "pip install Django==1.6
  - "pip install -e ."
script:
    coverage run --rcfile=.coverage.rc runtests.py
after_success:
    coveralls --config_file=.coverage.rc --coveralls_yaml=.coveralls.yml
