language: python

python:
  - 2.7
  - 3.5

env:
  - DJANGO=1.8.*
  - DJANGO=1.9.*
  - DJANGO=1.10.*

before_install:
  - pip install codecov

install:
  - pip install django==$DJANGO
  - pip install -e .

script:
  - coverage run runtests.py

after_success:
  - codecov
